services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kotlin_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=verysecurepassword123
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver

  db:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=verysecurepassword123
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./database_scripts:/docker-entrypoint-initdb.d